export const GET_CATEGORY_COURSES_REQUEST = "LAY_DANH_MUC_KHOC_HOC_REQUEST";
export const GET_CATEGORY_COURSES_SUCCESS = "LAY_DANH_MUC_KHOC_HOC_SUCCESS";
export const GET_CATEGORY_COURSES_ERR = "LAY_DANH_MUC_KHOC_HOC_ERR";

export const GET_CATEGORY_COURSES_DETAIL_REQUEST = "LAY_CHI_TIET_DANH_MUC_KHOC_HOC_REQUEST";
export const GET_CATEGORY_COURSES_DETAIL_SUCCESS = "LAY_CHI_TIET_DANH_MUC_KHOC_HOC_SUCCESS";
export const GET_CATEGORY_COURSES_DETAIL_ERR = "LAY_CHI_TIET_DANH_MUC_KHOC_HOC_ERR";

export const GET_COURSES_LIST_REQUEST = "LAY_DANH_SACH_KHOA_HOC_REQUEST";
export const GET_COURSES_LIST_SUCCESS = "LAY_DANH_SACH_KHOA_HOC_SUCCESS";
export const GET_COURSES_LIST_ERR = "LAY_DANH_SACH_KHOA_HOC_ERR";

export const SEARCH_COURSES_REQUEST = "SEARCH_COURSES_REQUEST";
export const SEARCH_COURSES_SUCCESS= "SEARCH_COURSES_SUCCESS";
export const SEARCH_COURSES_ERR = "SEARCH_COURSES_ERR";

export const GET_COURSES_DETAIL_REQUEST = "GET_COURSES_DETAIL_REQUEST";
export const GET_COURSES_DETAIL_SUCCESS= "GET_COURSES_DETAIL_SUCCESS";
export const GET_COURSES_DETAIL_ERR = "GET_COURSES_DETAIL_ERR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERR = "SIGNUP_ERR";

export const SIGNIN_REQUEST ="SIGNIN_REQUEST";
export const SIGNIN_SUCCESS ="SIGNIN_SUCCESS";
export const SIGNIN_ERR ="SIGNIN_ERR";

export const LOGOUT="LOGOUT"

export const GET_USER_INFOR_REQUEST= "GET_USER_INFOR_REQUEST";
export const GET_USER_INFOR_SUCCESS= "GET_USER_INFOR_SUCCESS";
export const GET_USER_INFOR_ERR= "GET_USER_INFOR_ERR";

export const GHI_DANH_KHOA_HOC_REQUEST = "GHI_DANH_KHOA_HOC_REQUEST";
export const GHI_DANH_KHOA_HOC_SUCCESS= "GHI_DANH_KHOA_HOC_SUCCESS";
export const GHI_DANH_KHOA_HOC_ERR = "GHI_DANH_KHOA_HOC_ERR";


