export const GET_CATEGORY_COURSES_REQUEST = "LAY_DANH_MUC_KHOC_HOC_REQUEST";
export const GET_CATEGORY_COURSES_SUCCESS = "LAY_DANH_MUC_KHOC_HOC_SUCCESS";
export const GET_CATEGORY_COURSES_ERR = "LAY_DANH_MUC_KHOC_HOC_ERR";

export const GET_CATEGORY_COURSES_DETAIL_REQUEST =
  "LAY_CHI_TIET_DANH_MUC_KHOC_HOC_REQUEST";
export const GET_CATEGORY_COURSES_DETAIL_SUCCESS =
  "LAY_CHI_TIET_DANH_MUC_KHOC_HOC_SUCCESS";
export const GET_CATEGORY_COURSES_DETAIL_ERR =
  "LAY_CHI_TIET_DANH_MUC_KHOC_HOC_ERR";

export const GET_COURSES_LIST_REQUEST = "LAY_DANH_SACH_KHOA_HOC_REQUEST";
export const GET_COURSES_LIST_SUCCESS = "LAY_DANH_SACH_KHOA_HOC_SUCCESS";
export const GET_COURSES_LIST_ERR = "LAY_DANH_SACH_KHOA_HOC_ERR";

export const SEARCH_COURSES_REQUEST = "SEARCH_COURSES_REQUEST";
export const SEARCH_COURSES_SUCCESS = "SEARCH_COURSES_SUCCESS";
export const SEARCH_COURSES_ERR = "SEARCH_COURSES_ERR";

export const GET_COURSES_LIST_PAGIN_REQUEST = "GET_COURSES_LIST_PAGIN_REQUEST"
export const GET_COURSES_LIST_PAGIN_SUCCESS = "GET_COURSES_LIST_PAGIN_SUCCESS";
export const GET_COURSES_LIST_PAGIN_ERR = "GET_COURSES_LIST_PAGIN_ERR";

export const GET_COURSES_DETAIL_REQUEST = "GET_COURSES_DETAIL_REQUEST";
export const GET_COURSES_DETAIL_SUCCESS = "GET_COURSES_DETAIL_SUCCESS";
export const GET_COURSES_DETAIL_ERR = "GET_COURSES_DETAIL_ERR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERR = "SIGNUP_ERR";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERR = "SIGNIN_ERR";

export const LOGOUT = "LOGOUT";

export const GET_USER_INFOR_REQUEST = "GET_USER_INFOR_REQUEST";
export const GET_USER_INFOR_SUCCESS = "GET_USER_INFOR_SUCCESS";
export const GET_USER_INFOR_ERR = "GET_USER_INFOR_ERR";

export const GHI_DANH_KHOA_HOC_REQUEST = "GHI_DANH_KHOA_HOC_REQUEST";
export const GHI_DANH_KHOA_HOC_SUCCESS = "GHI_DANH_KHOA_HOC_SUCCESS";
export const GHI_DANH_KHOA_HOC_ERR = "GHI_DANH_KHOA_HOC_ERR";

export const XOA_KHOA_HOC_REQUEST = "XOA_KHOA_HOC_REQUEST";
export const XOA_KHOA_HOC_SUCCESS = "XOA_KHOA_HOC_SUCCESS";
export const XOA_KHOA_HOC_ERRR = "XOA_KHOA_HOC_ERRR";

export const XOA_KHOA_HOC_LOCAL_REQUEST = "XOA_KHOA_HOC_LOCAL_REQUEST";
export const XOA_KHOA_HOC_LOCAL_SUCCESS = "XOA_KHOA_HOC_LOCAL_SUCCESS";
export const XOA_KHOA_HOC_LOCAL_ERRR = "XOA_KHOA_HOC_LOCAL_ERRR";
//Danh sách người dùng chưa ghi danh theo khóa học
export const DANH_SACH_CHO_XET_DUYET_THEO_MA_REQUEST =
  "DANH_SACH_CHO_XET_DUYET_THEO_MA_REQUEST";

export const DANH_SACH_CHO_XET_DUYET_THEO_MA_SUCCESS =
  "DANH_SACH_CHO_XET_DUYET_THEO_MA_SUCCESS";
export const DANH_SACH_CHO_XET_DUYET_THEO_MA_ERR =
  "DANH_SACH_CHO_XET_DUYET_THEO_MA_ERR";
//Danh sách người dùng đã ghi danh theo khóa học
  export const DANH_SACH_DA_XET_DUYET_THEO_MA_REQUEST =
  "DANH_SACH_DA_XET_DUYET_THEO_MA_REQUEST";

export const DANH_SACH_DA_XET_DUYET_THEO_MA_SUCCESS =
  "DANH_SACH_DA_XET_DUYET_THEO_MA_SUCCESS";
export const DANH_SACH_DA_XET_DUYET_THEO_MA_ERR =
  "DANH_SACH_DA_XET_DUYET_THEO_MA_ERR";
  //Danh sách người dùng chưa ghi danh theo khóa học
  export const DANH_SACH_CHƯA_XET_DUYET_THEO_MA_REQUEST =
  "DANH_SACH_CHƯA_XET_DUYET_THEO_MA_REQUEST";

export const DANH_SACH_CHƯA_XET_DUYET_THEO_MA_SUCCESS =
  "DANH_SACH_CHƯA_XET_DUYET_THEO_MA_SUCCESS";
export const DANH_SACH_CHƯA_XET_DUYET_THEO_MA_ERR =
  "DANH_SACH_CHƯA_XET_DUYET_THEO_MA_ERR";
export const THEM_KHOA_HOC_REQUEST = "THEM_KHOA_HOC_REQUEST";
export const THEM_KHOA_HOC_SUCCESS = "THEM_KHOA_HOC_SUCCESS";
export const THEM_KHOA_HOC_FAIL = "THEM_KHOA_HOC_FAIL";


