export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_ERR = "GET_USER_LIST_ERR";

export const CHANGE_PASSWORD_REQUEST  = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERR  = "CHANGE_PASSWORD_ERR";

export const ADD_USER_REQUEST  = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERR  = "ADD_USER_ERR";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_ERR = "SEARCH_USER_ERR";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS= "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERR = "UPDATE_USER_ERR";

export const GET_USER_All_LIST_REQUEST = "GET_USER_All_LIST_REQUEST";
export const GET_USER_All_LIST_SUCCESS = "GET_USER_All_LIST_SUCCESS";
export const GET_USER_All_LIST_ERR = "GET_USER_All_LIST_ERR";

export const DSKH_DA_GHI_DANH_REQUEST = "DSKH_DA_GHI_DANH_REQUEST";
export const  DSKH_DA_GHI_DANH_SUCCESS = "DSKH_DA_GHI_DANH_SUCCESS";
export const DSKH_DA_GHI_DANH_ERR = "DSKH_DA_GHI_DANH_ERR";

export const DSKH_CHUA_GHI_DANH_REQUEST = "DSKH_CHUA_GHI_DANH_REQUEST";
export const  DSKH_CHUA_GHI_DANH_SUCCESS = "DSKH_CHUA_GHI_DANH_SUCCESS";
export const DSKH_CHUA_GHI_DANH_ERR = "DSKH_CHUA_GHI_DANH_ERR";

export const DSKH_CHO_GHI_DANH_REQUEST = "DSKH_CHO_GHI_DANH_REQUEST";
export const  DSKH_CHO_GHI_DANH_SUCCESS = "DSKH_CHO_GHI_DANH_SUCCESS";
export const DSKH_CHO_GHI_DANH_ERR = "DSKH_CHO_GHI_DANH_ERR";
